/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUnparkRouteImport } from './routes/_app.unpark'
import { Route as AppTicketsRouteImport } from './routes/_app.tickets'
import { Route as AppSlotsRouteImport } from './routes/_app.slots'
import { Route as AppRevenueRouteImport } from './routes/_app.revenue'
import { Route as AppReservedRouteImport } from './routes/_app.reserved'
import { Route as AppParkRouteImport } from './routes/_app.park'
import { Route as AppHistoryRouteImport } from './routes/_app.history'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUnparkRoute = AppUnparkRouteImport.update({
  id: '/unpark',
  path: '/unpark',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppSlotsRoute = AppSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueRoute = AppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppReservedRoute = AppReservedRouteImport.update({
  id: '/reserved',
  path: '/reserved',
  getParentRoute: () => AppRoute,
} as any)
const AppParkRoute = AppParkRouteImport.update({
  id: '/park',
  path: '/park',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/history': typeof AppHistoryRoute
  '/park': typeof AppParkRoute
  '/reserved': typeof AppReservedRoute
  '/revenue': typeof AppRevenueRoute
  '/slots': typeof AppSlotsRoute
  '/tickets': typeof AppTicketsRoute
  '/unpark': typeof AppUnparkRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/history': typeof AppHistoryRoute
  '/park': typeof AppParkRoute
  '/reserved': typeof AppReservedRoute
  '/revenue': typeof AppRevenueRoute
  '/slots': typeof AppSlotsRoute
  '/tickets': typeof AppTicketsRoute
  '/unpark': typeof AppUnparkRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/park': typeof AppParkRoute
  '/_app/reserved': typeof AppReservedRoute
  '/_app/revenue': typeof AppRevenueRoute
  '/_app/slots': typeof AppSlotsRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/_app/unpark': typeof AppUnparkRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/history'
    | '/park'
    | '/reserved'
    | '/revenue'
    | '/slots'
    | '/tickets'
    | '/unpark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/history'
    | '/park'
    | '/reserved'
    | '/revenue'
    | '/slots'
    | '/tickets'
    | '/unpark'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/history'
    | '/_app/park'
    | '/_app/reserved'
    | '/_app/revenue'
    | '/_app/slots'
    | '/_app/tickets'
    | '/_app/unpark'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/unpark': {
      id: '/_app/unpark'
      path: '/unpark'
      fullPath: '/unpark'
      preLoaderRoute: typeof AppUnparkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/slots': {
      id: '/_app/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof AppSlotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revenue': {
      id: '/_app/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AppRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reserved': {
      id: '/_app/reserved'
      path: '/reserved'
      fullPath: '/reserved'
      preLoaderRoute: typeof AppReservedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/park': {
      id: '/_app/park'
      path: '/park'
      fullPath: '/park'
      preLoaderRoute: typeof AppParkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppParkRoute: typeof AppParkRoute
  AppReservedRoute: typeof AppReservedRoute
  AppRevenueRoute: typeof AppRevenueRoute
  AppSlotsRoute: typeof AppSlotsRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppUnparkRoute: typeof AppUnparkRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppParkRoute: AppParkRoute,
  AppReservedRoute: AppReservedRoute,
  AppRevenueRoute: AppRevenueRoute,
  AppSlotsRoute: AppSlotsRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppUnparkRoute: AppUnparkRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
